bot:
  token: "<bot token as string>"
  admin_id: <admin ID as int>

db:
  # строка подключения к базе данных
  dsn: "postgresql+psycopg://<database username>:<database password>@<host address>/<database name>"
  # Если указать true, то при создании движка параметр "echo" будет True,
  # что приведёт к выводу на экран расширенной информации о взаимодействии
  # SQLAlchemy и базы данных. В противном случае укажите false
  is_echo: <bool>
